version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql:5.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhatroot
      - MYSQL_PASSWORD=redhat123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 1234:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
