import os
os.system("clear") 
import socket 
import time

def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    return s.getsockname()[0]


print("Created by Harvinder Singh")
time.sleep(1)
print("""
          ######################
          #  @ @ @ @ @ @ @ @   #
          #               o    #
          #     SERVER   /|\   #
          #               |    #   
          #       BUFFET / \   #
          #  @ @ @ @ @ @ @ @   #
          #                    #   
          ######################
    

""")



time.sleep(1)
IP = get_ip_address()
print("Here's The Menu/-")
time.sleep(2)
print("""
HEY! USER WELCOME TO SERVERS BUFFET -generated by DOCKER \n
1 => Cloud Server
\n
2 => Web Server
\n
3 => CI SERVER
\n
4 => Ubuntu OS
\n
5 => Programming Environments
\n
6 => Exit
\n""")
x = input()

if x=='1':
  os.system("systemctl start docker") 
  os.chdir("/mycompose") 
  os.system("docker-compose up -d")
  os.system("firefox %s:1234"%IP)

elif x=='2': 
  
  os.system("systemctl start docker")
  os.chdir("/mycompose/webb")
  os.system("docker-compose up -d")
  os.system("firefox %s:8081"%IP)
elif x=='3': 
  
  os.system("systemctl start docker")
  os.chdir("/mycompose/Jenkins")
  os.system("bash Jenkins") 
  os.system("firefox %s:8082"%IP)
elif x=='4': 
  
  os.system("systemctl start docker")
  os.chdir("/mycompose/OS")
  os.system("bash cmmd") 
elif x=='5': 
  
  os.system("systemctl start docker")
  os.chdir("/mycompose/pl")
  print("""
        What Language would you prefer?
        >> Python..1
        >> C..2
        >> Java..3    
  """) 
  
  y=input()
  if y=='1':
    print("Enter Your file name: ",end='')
    fn=input()
    os.system("gedit %s.py"%fn)

  elif y=='2':
    print("Enter Your file name: ",end='')
    fn=input()
    os.system("gedit %s.c"%fn)
  elif y=='3':
    print("Enter Your file name: ",end='')
    fn=input()
    os.system("gedit %s.java"%fn)
  else:
    os.system("exit")

else:
  print("Hope To See You Soon!")
  os.system("clear")
  os.system("exit")
